const checkbox = document.getElementsByName("divStyle")[0];

const textFields = document.querySelectorAll(".textfield");

const button = document.getElementById("addButton");

const secretDiv = document.querySelector(".secretDiv");


function inputListener (e) {
    const name = e.target.name;
    const value = e.target.value;
    const html = `<p>Fältet "${name}" har värdet ${value}</p>`;
    return html;
}

textFields.forEach(field => {
  field.addEventListener('keydown', (e) => {
    if (e.key == 'Enter') {
      const html = inputListener(e);
      secretDiv.innerHTML = html;
      console.log(`Event generated by the textfield "${e.target.name}".`);
      e.preventDefault();
    }})
});

checkbox.addEventListener('change', () => {
    const colorField = document.querySelector("#color").value;
    secretDiv.style.backgroundColor = colorField;
    // console.log(colorField);
});

