/*Hämtar HTML-element som ska användas i koden*/
const checkbox = document.getElementsByName("divStyle")[0];
const textFields = document.querySelectorAll(".textfield");
const slayButton = document.getElementById("divSlayerButton");
const secretDiv = document.querySelector(".secretDiv");
const inputBox = document.querySelector('.box'); 
const heading = document.createElement('h1');
const mainElement = document.querySelector('main');

/* ***Styling*** */

/*H1*/
/*Rubrik för sidan*/
function styleHeading() {
heading.textContent = "Grupp 8 uppgift 1";            
mainElement.prepend(heading);                        
heading.style.textAlign = 'center';                  
heading.style.color = '#2e8bc0';
heading.style.textShadow = '2px 2px 5px #000';
heading.style.fontFamily = 'Verdana';
heading.style.marginTop = '20px';
heading.style.fontSize = '2em';
}
styleHeading();

/*Bakgrundsfärg på body*/
function styleBody() {
  document.body.style.backgroundColor = '#2c3e50';
  document.body.style.margin = '0';
  document.body.style.padding ='0';
  document.body.style.fontFamily ='Verdana';
}
styleBody();

function styleButton() {
  slayButton.style.fontFamily = 'Verdana';
  slayButton.style.fontSize = '15px';
  slayButton.style.backgroundColor = '#145da0';
  slayButton.style.color = 'white'; 
  slayButton.style.padding = '5px 15px'; 
  slayButton.style.border = 'none'; 
  slayButton.style.borderRadius = '5px'; 
  slayButton.style.marginTop = '20px';
}
styleButton();

function styleInputBox() {
  inputBox.style.backgroundColor = '#f0f0f0'; 
  inputBox.style.padding = '20px'; 
  inputBox.style.borderRadius = '10px'; 
  inputBox.style.boxShadow = '0 4px 8px #000'; 
  inputBox.style.maxWidth = '600px'; 
  inputBox.style.margin = '20px auto'; 
}
styleInputBox();

function styleSecretDiv() {
  secretDiv.style.width = 'display: flex'; 
  secretDiv.style.height = 'auto'; 
  secretDiv.style.margin = '15px auto'; 
  secretDiv.style.padding = '10px'; 
  secretDiv.style.border = '1px solid #ccc'; 
  secretDiv.style.borderRadius = '5px'; 
  secretDiv.style.backgroundColor = '#e6e6e6'; 
  secretDiv.style.boxSizing = 'border-box'; 
}
styleSecretDiv();

/*Uppgiften*/ 
function inputListener (e) {
  const name = e.target.name;
  const value = e.target.value;
  const html = `<p>Fältet "${name}" har värdet ${value}</p>`;
  return html;
}

textFields.forEach(field => {
  field.addEventListener('keydown', (e) => {
    if (e.key == 'Enter') {
      const html = inputListener(e);
      secretDiv.innerHTML = html;
      console.log(`Event generated by the textfield '${e.target.name}'.`);
    }})
  });
  
  checkbox.addEventListener('change', () => {
    const colorField = document.querySelector("#color").value;
    secretDiv.style.backgroundColor = colorField;
    console.log(`Elementet 'secretDiv' har ${colorField} som bakgrundsfärg.`);
  });
  
  slayButton.addEventListener('click', () => {
    secretDiv.remove();
  });
  

  /* slut på uppgiften*/ 
